services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: keycloak_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./kc_db_init.sh:/docker-entrypoint-initdb.d/kc_db_init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d keycloak_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:7-alpine'
    container_name: 'redis'
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    container_name: 'keycloak'
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres_pass
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
